spring:
  application:
    name: spring-data-post-management
  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5432/spring-data-post-management
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
     init:
      mode: always
server:
  port: 8080
